# Generated by Django 6.0 on 2026-01-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='current_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
