# Generated by Django 6.0 on 2026-01-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_pricehistory_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='target_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='target_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
