# Generated by Django 6.0 on 2026-01-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
